Add missing dependency on minijail to cromo.
cromo needs minijail at both compile-time and run-time, so it should have a
DEPEND / RDEPEND on it.

Without this fix, you get the following error when compiling cromo:
  sandbox.cc:7:34: fatal error: chromeos/libminijail.h: No such file or directory

BUG=chromium-os:22264
TEST=Check that emerging cromo pulls in minijail now.

Change-Id: I970a8687d9465b4191e90f354704c154a280fc2f
Reviewed-on: https://gerrit.chromium.org/gerrit/10870
Reviewed-by: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>
Commit-Ready: David James <davidjames@chromium.org>