cros-firmware: depend on vpd
Since the pack_firmware.sh code wants the target vpd, make sure we depend
on it.  Otherwise, trying to build just the firmware ends up failing with
the error message:
	ERROR: Cannot find tool program to bundle: vpd

BUG=chromium-os:19140
TEST=`cbuildbot {{x86,amd64}-generic,daisy}-paladin {amd64,arm,x86}-generic-full stout-release` passed
TEST=`./build_packages virtual/chromeos-firmware` works with an otherwise empty tree

Change-Id: I2476816c4c34f193e60d702af9fc0570da6bdc65
Reviewed-on: https://gerrit.chromium.org/gerrit/33273
Reviewed-by: Puneet Kumar <puneetster@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>