Revert "gcc: fix race conditions when rotating log files"
This reverts commit f47cf1c6cc3e27bff726a94c0aee9691b97639e7

broke the cros-sdk:
 * Auto adding -march=i686 to CFLAGS #185404
Traceback (most recent call last):
  File "/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/gcc-bin/4.6.x-google/i686-pc-linux-gnu-gcc", line 201, in <module>
    fd = lock(log_file)
  File "/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/gcc-bin/4.6.x-google/i686-pc-linux-gnu-gcc", line 193, in lock
    os.fchmod(fd, 0666)
OSError: [Errno 1] Operation not permitted
Change-Id: I920aae574cffcc83d56b41f245df4e571e8045e1
Reviewed-on: https://gerrit.chromium.org/gerrit/27611
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>