stressapptest: Force building with libstdc++.
stressapptest does not build with libc++ because of
compilation errors. Force use of libstdc++ to avoid the errors.

In file included from sat.cc:44:
In file included from ./disk_blocks.h:29:
./sattypes.h:33:17: error: expected namespace name
using namespace __gnu_cxx;  // NOLINT

BUG=chromium:747053
TEST=stressapptest builds with libstdc++.

Change-Id: I60045a2d701a89af46706016dde0f5e7daace3de
Reviewed-on: https://chromium-review.googlesource.com/580072
Commit-Ready: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Reviewed-by: Nick Sanders <nsanders@chromium.org>