chromeos-chrome: DEPEND on libdrm for ARM
At present, all arm builds of Chrome use v4l2 for video decode
acceleration.  Support is built into the same binary for all arm boards,
including tegra and exynos.  The exynos implementation
(exynos_v4l2_video_device.cc) includes libdrm/drm_fourcc.h since it needs
to use DRM_FORMAT_NV12.

Thus, all ChromeOS ARM Chrome DEPENDS on libdrm (even arm boards whose
driver stack does not otherwise use libdrm).

This fixes the following build error:

../../content/common/gpu/media/exynos_v4l2_video_device.cc:7:31: fatal error: libdrm/drm_fourcc.h: No such file or directory
 #include <libdrm/drm_fourcc.h>

Signed-off-by: Daniel Kurtz <djkurtz@chromium.org>

BUG=chromium:390270
TEST=tryjob on nyan.*-chrome-pfq

Change-Id: If53a2754b59bcc5e28bba985aa18ec6541afe283
Reviewed-on: https://chromium-review.googlesource.com/206183
Reviewed-by: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Daniel Kurtz <djkurtz@chromium.org>
Commit-Queue: Daniel Kurtz <djkurtz@chromium.org>