Revert "Update pygobject from 2.18.0 to 2.20.0 since 2.18 does not work with glib 2.26."
error: pygobject-2.20.0: /bin/sh: ../gobject/generate-constants: cannot execute binary file
For ARM, it seems that we have to port the cross-compile patch from 2.18 to 2.20.

This reverts commit 819e6994866073f5024d3b8a4741aa66a4147f1a.

BUG=chromium-os:9684
TEST=none
TBR=satorux

Review URL: http://codereview.chromium.org/5426001

Change-Id: I0014b32cdec6ef9b6e33c1b5b56caa6ce6cc13e0