OpenCV: Force building with libstdc++.
OpenCV still needs to be built with libstdc++ because of following errors
on ARM. It uses GNU extension header files which are not provided by libc++.

OpenCV-2.3.0/modules/core/include/opencv2/core/operations.hpp:62:16: fatal error:
       'ext/atomicity.h' file not found
       #include <ext/atomicity.h>
                ^~~~~~~~~~~~~~~~~

BUG=chromium:747060
TEST=OpenCV builds

Change-Id: I8b8d34991cecfb4e61aa2aa1e63210053ff94e80
Reviewed-on: https://chromium-review.googlesource.com/648746
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>
Trybot-Ready: Manoj Gupta <manojgupta@chromium.org>