dev-install: use an empty root when building package depgraphs
This avoids issues with the /var/db/pkg dir being rewritten in parallel
with the main emerge causing crashes:

Traceback (most recent call last):
  File "/usr/bin/emerge", line 51, in <module>
    retval = emerge_main()
...
KeyError: u'net-wireless/wpa_supplicant-0.7.2-r158'
 * ERROR: chromeos-base/dev-install-0.0.1-r699::chromiumos failed (compile phase):

BUG=chromium:202477
TEST=`emerge-link dev-install` works
TEST=`cbuildbot amd64-generic-full` works

Change-Id: I0a1a11a4e0af77264f37fc43759c1c5b195a83a9
Reviewed-on: https://chromium-review.googlesource.com/227591
Reviewed-by: Chris Sosa <sosa@chromium.org>
Commit-Queue: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>