Fix gcc 4.8 build broken for python 2.7.
The error was reported while building chromeos-chrome - "error: 'PyArg_ParseTuple' is an unrecognized format function type".

The issue is that '-Wformat' is no longer included by default in gcc 4.8. The solution is to add '-Wformat' explictly to configure.

For GCC 4.7, since '-Wformat' is enabled by default, the modification has no impact to current gcc.

Below shows the difference between gcc 4.7 and gcc 4.8.

    void f(char*,...)__attribute((format(PyArg_ParseTuple, 1, 2)));
    int
    main ()
    {

      ;
      return 0;
    }

    With gcc 4.7:
    $ gcc -Werror /tmp/foo.c
    /tmp/foo.c:1:1: error: ‘PyArg_ParseTuple’ is an unrecognized format function type [-Werror=format]
    cc1: all warnings being treated as errors
    $ echo $?
    1

    With gcc 4.8:
    $ ~/coding/gcc-python/gcc-svn-trunk/install/bin/gcc -Werror /tmp/foo.c
    $ echo $?
    0

    but on adding -Wall:
    $ ~/coding/gcc-python/gcc-svn-trunk/install/bin/gcc -Werror -Wall /tmp/foo.c
    /tmp/foo.c:1:1: error: ‘PyArg_ParseTuple’ is an unrecognized format function type [-Werror=format=]
     void f(char*,...)__attribute((format(PyArg_ParseTuple, 1, 2)));
     ^
    cc1: all warnings being treated as errors
    $ echo $?
    1

    or indeed just -Wformat:

    $ ~/coding/gcc-python/gcc-svn-trunk/install/bin/gcc -Werror -Wformat /tmp/foo.c
    /tmp/foo.c:1:1: error: ‘PyArg_ParseTuple’ is an unrecognized format function type [-Werror=format=]
     void f(char*,...)__attribute((format(PyArg_ParseTuple, 1, 2)));
     ^
    cc1: all warnings being treated as errors
    $ echo $?
    1

TEST=built successfully using gcc 4.7 and gcc 4.8.
BUG=None

Change-Id: I40f9da4c75c3280ea577ac6c97bb6a04b7a4ba58
Reviewed-on: https://gerrit.chromium.org/gerrit/47153
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Commit-Queue: Han Shen <shenhan@google.com>
Tested-by: Han Shen <shenhan@google.com>