Fix missing dependency on gmock.
This fixes the following error.

util_unittest.cc:6:25: fatal error: gmock/gmock.h: No such file or
directory

BUG=none
TEST=Trybot run.

Change-Id: I59e0dd23588cf8a0b7e77fd51674b4db8da4fb74
Reviewed-on: https://gerrit.chromium.org/gerrit/37001
Reviewed-by: Don Garrett <dgarrett@chromium.org>
Commit-Ready: David James <davidjames@chromium.org>
Tested-by: David James <davidjames@chromium.org>