libchromeos: add missing openssl depend
The code uses openssl, so we need to depend on it, or we try to emerge
it before openssl is available and we get a build failure:

>>> Compiling source in .../libchromeos-0.0.1 ...
scons: Reading SConscript files ...
Package openssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `openssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'openssl' found
OSError: 'pkg-config-lumpy --cflags --libs glib-2.0 openssl' exited 1:
...
 *       scons libchromeos.a || die "libchromeos.a compile failed."

BUG=None
TEST=`emerge-lumpy -C openssl && emerge-lumpy libchromeos` works

Change-Id: I09b342501525b4389768a45092bd865c9994a4da
Reviewed-on: https://gerrit.chromium.org/gerrit/13610
Reviewed-by: Satoru Takabayashi <satorux@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>