[root-certificates] name installed certs by hash
Previously, we were installing the certs by name; however, this makes gmerge
combust when installing them as follows:

Traceback (most recent call last):
  File "/usr/local/lib/portage/pym/portage/dbapi/_MergeProcess.py", line 246, in _spawn
    prev_mtimes=self.prev_mtimes, counter=counter)
  File "/usr/local/lib/portage/pym/portage/dbapi/vartree.py", line 4272, in merge
    counter=counter)
  File "/usr/local/lib/portage/pym/portage/dbapi/vartree.py", line 3351, in treewalk
    eerror(portage._merge_unicode_error(unicode_errors))
AttributeError: 'module' object has no attribute '_merge_unicode_error'

Therefore, rename them to their fingerprint (in hex).

BUG=chromium-os:39198
TEST=adhoc
'gmerge root-certificates' works now.

Change-Id: If49c5a8bfeaea97c128f3e4094b44ad2a75255b6
Signed-off-by: Elly Fong-Jones <ellyjones@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/44638
Reviewed-by: Richard Barnette <jrbarnette@chromium.org>