Update portage to create directories atomically.
Portage should use the ensure_dirs function instead of os.makedirs to create
directories, because this function ensures atomicity. It prevents failures
when more than one process tries to create the same directory.

This fixes a crash bug reported by msb:
[...]
  File "/usr/lib64/portage/pym/portage/dbapi/vartree.py", line 3258, in _merge
    self.vartree.dbapi._bump_mtime(self.mycpv)
  File "/usr/lib64/portage/pym/portage/dbapi/vartree.py", line 152, in _bump_mtime
    os.makedirs(catdir)
  File "/usr/lib64/portage/pym/portage/__init__.py", line 210, in __call__
    rval = self._func(*wrapped_args, **wrapped_kwargs)
  File "/usr/lib64/python2.6/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/msb/trunk/src/build/images/x86-generic/0.8.63.2010_08_03_1844-a1/rootfs//var/db/pkg/x11-proto'

BUG=chromium-os:5366
TEST=build_packages && build_image

Review URL: http://codereview.chromium.org/3113014