Adjust U-Boot ebuild to work with new upstream tree
Fix three issues which prevent our ebuild from building the new 'upstream'
tree.

1. We are carrying patches that make U-Boot use <stdint.h>, and these have
not been sent upstream. The workaround so far is to define USE_STDINT=1
to enable this, so the ebuild must do so. Otherwise build errors appear
since uintptr_t is defined in two places.

E.g.:

In file included from /usr/lib/gcc/i686-pc-linux-gnu/4.7.x-google/include/stdint.h:5:0,
                 from ../../vboot_reference/firmware/include/tlcl.h:14,
                 from cmd_cros_tpm_test.c:9:
/usr/lib/gcc/i686-pc-linux-gnu/4.7.x-google/include/stdint-gcc.h:86:22: error: conflicting types for 'uintptr_t'
In file included from ../../include/image.h:36:0,
                 from ../../include/common.h:116,
                 from cmd_cros_tpm_test.c:6:

2. The u-boot.img file is no longer generated. It was needed for
beaglebone, but should not be enabled for other builds. For now, remove it.
If it is re-enabled, it should be enabled just for beaglebone.

3. The USE=dev flag is intended to remove extraneous output, of which there
is about 1.3MB or 42K lines.

Vboot's Makefile recently became more verbose, so we need to quieten that
down also.

BUG=chrome-os-partner:19735
TEST=manual
$ emerge-link chromeos-u-boot
$ USE=dev emerge-link chromeos-u-boot

See that in the second case, the vboot output does not appear:

make[1]: Entering directory `/build/link/tmp/portage/sys-boot/chromeos-u-boot-9999/work/chromeos-u-boot-9999/vboot_reference'
    CC            firmware/lib/cryptolib/padding.o
    CC            firmware/lib/cryptolib/rsa.o
    CC            firmware/lib/cryptolib/rsa_utility.o
...

USE=dev emerge-daisy chromeos-u-boot

(to test that it builds)

Change-Id: I6db5f9cf890036c56daa1e9c9517cf5842117830
Signed-off-by: Simon Glass <sjg@chromium.org>
Reviewed-on: https://gerrit.chromium.org/gerrit/56860