Revert "Updating clang ebuilds to 3.1 r151057 in accordance with Gentoo repo."
This reverts commit c5169fd31e30ea7953faf57bd79c59dd7ac5e7c0

Seems to have broken the cros-sdk bot:

http://build.chromium.org/p/chromiumos/builders/chromiumos%20sdk/builds/1290/steps/cbuildbot/logs/stdio

mesa-7.11_p4-r6:
gallivm/lp_bld_misc.cpp: In function 'void lp_set_target_options()':
gallivm/lp_bld_misc.cpp:99:4: error: 'NoExcessFPPrecision' is not a member of 'llvm'
gallivm/lp_bld_debug.cpp: In function 'void lp_disassemble(void const*)':
gallivm/lp_bld_debug.cpp:254:80: error: no matching function for call to 'llvm::Target::createTargetMachine(std::string&, std::string, char const [1]) const'
..........

Change-Id: Ia1947bce4312a3ada09bf5836ff20db8720f3a56
Reviewed-on: https://gerrit.chromium.org/gerrit/18056
Reviewed-by: Stéphane Marchesin <marcheu@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>