Revert "xf86-input-synaptics: enable cros-workon."
This reverts commit 6bffceb18eea41896644133f03ef57e9b171bdbd.

The xf86-input-synaptics ebuilds continue to break cbuildbot:
ERROR: Found multiple unstable ebuilds in /home/chrome-bot/trunk/src/third_party/chromiumos-overlay/x11-drivers/xf86-input-synaptics

BUG=
TEST=

Review URL: http://codereview.chromium.org/6330016

Change-Id: I7c8e11a36900d9bead7b297343b8d8ac9cc40e03