cros-kernel: Set CONFIG_FRAME_WARN=0 for builds with KASAN
After switching from gcc to clang kernel builds with KASAN generate
warnings about stack space usage:

drivers/net/wireless/ar10k/mac80211/mlme.c:3574:6: error: stack frame
  size of 3520 bytes in function 'ieee80211_sta_rx_queued_mgmt' [-Werror,
  -Wframe-larger-than=]
void ieee80211_sta_rx_queued_mgmt(struct ieee80211_sub_if_data *sdata,
     ^
1 error generated.

KASAN is known to increase memory usage and clang apparently is worse
in this aspect than gcc. By default Kconfig disables the stack size
warning when KASAN is enabled, however the CrOS kernel configuration
specifies a non-zero value for CONFIG_FRAME_WARN regardless of KASAN.
Revert to the default by setting CONFIG_FRAME_WARN=0 when KASAN is
enabled.

BUG=chromium:781317
TEST=integrate latest FROMLIST patches for KASAN with clang
 (1st: https://patchwork.kernel.org/patch/10083717/)
 USE="kasan" emerge-kevin chromeos-kernel-4_4
   => no warnings about stack frame size

Change-Id: I276535c8f97eccc7f0f16dba2f927af64e212e57
Reviewed-on: https://chromium-review.googlesource.com/802077
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>