Revert "xf86-input-synaptics: enable cros-workon."
This reverts commit a5b4f536f40e94874eaa8fa74fb6fde3334a0c7c.

cbuildbot keeps complaining:
ERROR: Found multiple unstable ebuilds in
/home/chrome-bot/trunk/src/third_party/chromiumos-overlay/x11-drivers/xf86-input-synaptics

Reverting until resolved.

BUG=
TEST=

Review URL: http://codereview.chromium.org/6264018

Change-Id: Iad5cfea5c6035648ba7318bbdbee17037f75637c