Checks whether all function pointers in platform/cros/load.cc are initialized correctly. The script should automatically detect a mistake like http://codereview.chromium.org/4055001 .
Example output from the checker would be like:

----------
(cros-chroot) yusukes@harapeko ~/trunk/src/scripts $ emerge-x86-generic libcros
...
ERROR: INIT_FUNC for RequestShutdown is missing!
ERROR: INIT_FUNC for RequestRestart is missing!
 * ERROR: chromeos-base/libcros-9999 failed:
 *   INIT_FUNC(s) are missing from load.cc.
...
>>> Failed to emerge chromeos-base/libcros-9999 for /build/x86-generic/, Log file:
----------

BUG=none
TEST=ran the script via 'emerge-x86-generic libcros' with both good and bad load.cc.

Change-Id: I48bf543c7a00d65e1fefe5748d591e90ad131ea3

Review URL: http://codereview.chromium.org/4014005