Revert "net-misc/curl: use curl 7.23.1-r1"
This reverts commit fafc76b01b7d7d9548d8d7983c76797298e7a9ed

Trouble building o3d

o3d-100004: breakpad/src/common/linux/libcurl_wrapper.cc:32:24: fatal error: curl/types.h: No such file or directory
Change-Id: Ic986e6de8a9d955e80cb2dcc62b68d192e9e153c
Reviewed-on: https://gerrit.chromium.org/gerrit/12478
Commit-Ready: Jason Glasgow <jglasgow@chromium.org>
Tested-by: Jason Glasgow <jglasgow@chromium.org>
Reviewed-by: David James <davidjames@chromium.org>