Revert "Removed crosstool-overlay and hardened-dev overlays."
This reverts commit 432a1b8b35e2dc324df371fd6bccec9aa39a6550.
We need to revert it because it does not compile, even with the fixes
listed below. Here is the error:

In file included from ../nptl/sysdeps/unix/sysv/linux/i386/fork.c:31:
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c: In function '__libc_fork':
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:209: error: can't find
a register in class 'BREG' while reloading 'asm'
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:120: error: 'asm'
operand has impossible constraints
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:126: error: 'asm'
operand has impossible constraints
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:130: error: 'asm'
operand has impossible constraints
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:196: error: 'asm'
operand has impossible constraints
../nptl/sysdeps/unix/sysv/linux/i386/../fork.c:209: error: 'asm'
operand has impossible constraints

Also revert "Fix arm builds that don't have arm in the name (e.g. st1q)"
This reverts commit 6717aee11dc9fe73e82ceaed42a5e0401b3c4aa9.
Also revert "Update board logic to check for variants."
This reverts commit fb299ab524946d21a5c98b5a026df32f34cd1385.

Review URL: http://codereview.chromium.org/3162012