chromeos-debugd: depend on libchromeos
This package uses headers from libchromeos, but doesn't depend on it, so
sometimes it fails on the builders (but we don't notice because the the
retry step works).

For example, these recent build logs show it clearly:
	http://build.chromium.org/p/chromiumos/builders/amd64%20corei7%20full/builds/581/
	http://build.chromium.org/p/chromiumos/builders/tegra2%20full/builds/1529/

chromeos-debugd-0.0.0-r7:
In file included from .../chromeos-debugd-0.0.0/src/process_with_id.cc:5:0:
.../chromeos-debugd-0.0.0/src/process_with_id.h:8:30:
	fatal error: chromeos/process.h: No such file or directory
compilation terminated.
make[2]: *** [process_with_id.o] Error 1

BUG=None
TEST=`./build_packages --board=amd64-corei7 --fast --nousepkg` works

Change-Id: I79cb0dfef67afa58a5a34286eb51ab13bb158077
Reviewed-on: https://gerrit.chromium.org/gerrit/14285
Reviewed-by: Elly Jones <ellyjones@chromium.org>
Commit-Ready: Mike Frysinger <vapier@chromium.org>
Tested-by: Mike Frysinger <vapier@chromium.org>